### PR TITLE
Defined refinements of coverings

### PR DESCRIPTION
**Pull request by louismntnu**

### CODE REVIEW

**Comment by louismntnu** [comment]
@fredrik-bakke Something is wrong with my code in refinements-coverings-Locales.lagda.md that I can't figure out. When type checking I get non-resolved goals, but I don't understand why. Perhaps something is wrong with my definitions.

**Comment by fredrik-bakke** [comment]
I'll look at it in a couple of minutes!

**Comment by fredrik-bakke** [comment]
The problem is that there's an implicit argument that Agda is unable to infer the contents of. You've left the underlying locale implicit for `is-refinement-covering-Locale` and `refinement-covering-Locale`, but generally there won't be enough information around for Agda to infer the entire structure of the underlying locale. For instance, in your case, it should be able to infer the underlying type of the locale as that is lying around in your contexts. However, in general, there are multiple possible locale structures on a given type, and Agda won't make any assumptions about what that structure should be unless it is required. Thus, I suggest making these arguments explicit.

**Comment by fredrik-bakke** [comment]
For the future, the same is true when using most structured types. For instance, `Prop`s are rarely inferable.

**Comment by louismntnu** [comment]
Thanks! That's very helpful

**Comment by fredrik-bakke** [comment]
By the way, I realize I may have misunderstood you yesterday. I think we should redefine coverings in terms of `is-least-upper-bound`, as this is more readily generalizable. Later, our current definition can be a characterization of coverings in locales.

**Comment by louismntnu** [comment]
You mean instead of using the join? I can do that.

Right now, I have another issue. I've moved on to defining finite refinements (in `finite-refinement-covering-locales`) and now the system can't solve constraints. Again, I'm not sure what went wrong.

**Comment by fredrik-bakke** [comment]
Your best bet is just to start passing some of the implicit arguments to see when Agda is happy. For instance, if the argument is named `x`, you can pass by name using `{x = ...}` (or you can pass it by position, but then you risk having to specify some other implicit arguments as well). When you've found the culprit(s), you can make an evaluation of whether it should be made explicit, or whether you think Agda will be able to infer it often enough to leave it implicit and just pass it using `{...}` when necessary.

**Comment by louismntnu** [comment]
You mean pass it to `is-finite-refinement-covering-Locale` or to `indexing-family-refinement-covering-Locale`? And do you mean adding something like `{L = L}`? I'm really not sure I follow.

**Comment by fredrik-bakke** [comment]
If the problem is an implicit locale then `{L = L}` would probably be correct, yes. I don't know what the state of your local repository is, so it is hard to guess what the exact problem is. If it is the locale you're taking implicitly, I would suggest making it always explicit as per the previous discussion.

**Comment by louismntnu** [comment]
The code that I'm referring to should all be in this pull request. And yes, L has already been made explicit. I tried making more things explicit, but to no effect.

**Comment by fredrik-bakke** [comment]
Ah, Agda is struggling to infer `v` in `domain-refinement-covering-Locale`. You should probably make it explicit.

**Comment by fredrik-bakke** [comment]
To make the current version typecheck, you would need to write

```agda
  is-finite-refinement-covering-Locale :
    (r : refinement-covering-Locale L v) → UU l2
  is-finite-refinement-covering-Locale r =
    is-finite (domain-refinement-covering-Locale L {v = v} r)
```

**Comment by fredrik-bakke** [comment]
The troubling definition should be highlighted in yellow (or a different color based on your theme), and the troubling file will be linked to in the Agda window.

**Comment by louismntnu** [comment]
Nice, it works! Thank's again.

**Comment by fredrik-bakke** [comment]
Could we continue discussions over at Discord to keep it organized and have Fernando in the loop? 😅

**Comment by fredrik-bakke** [comment]
For your information, if your goal is to get the stuff in Quasicompact merged into agda-unimath, you don't have to merge it into Coherent-locales first. You can simply make a PR from Quasicompact into agda-unimath's master branch.

**Comment by louismntnu** [comment]
I see. But I think I'll submit another pull request when I'm finished with defining coherent locales.

**Pull request merged**
